name: "Zuzulka Home Ops"
description: "Home Assistant Board Log API"
version: "1.0.24"
slug: "zuzulka_home_ops"
arch:
  - amd64
init: false
ingress: true
ingress_port: 8000
panel_icon: "mdi:book-open-page-variant"
panel_title: "Zuzulka"
